CREATE DATABASE IF NOT EXISTS TaskApp;

USE TaskApp;

CREATE TABLE IF NOT EXISTS Users(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(75) NOT NULL,
    password VARCHAR(125) NOT NULL
);