version: "3.8"
services:
 backend:
  container_name: task-app-container
  depends_on :
    - mysqlDb
  build:
   context: .
   dockerfile: Dockerfile
  restart: always
  ports:
   - 8082:8082
 mysqlDb:
  image: mysql
  restart: always
  container_name : mysql-task-container
  ports:
    - 3308
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  volumes:
    - ./myDb:/var/lib/mysql

  